<?php

namespace app\models\event;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Expression;
use app\models\Comment;
use app\models\Profile;
use app\models\book\Book;

/**
 * This is the model class for table "{{%event}}".
 *
 * @property integer $id
 * @property string  $name
 * @property string  $description
 * @property integer $date
 * @property integer $bookId
 * @property integer $publish
 * @property integer $creatorId
 * @property string  $createDate
 */
class Event extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%event}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [
                [
                    'publish',
                    'creatorId',
                    'bookId',
                ],
                'integer',
            ],
            [
                [
                    'createDate',
                    'date',
                ],
                'safe',
            ],
            [
                [
                    'name',
                    'description',
                ],
                'string',
            ],
            [
                ['bookId'],
                'exist',
                'skipOnError'     => true,
                'targetClass'     => Book::class,
                'targetAttribute' => ['bookId' => 'id'],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'          => 'ID',
            'name'        => 'Name',
            'description' => 'Description',
            'date'        => 'Date',
            'publish'     => 'Publish',
            'creatorId'   => 'Creator ID',
            'createDate'  => 'Create Date',
        ];
    }

    public function getEclink()
    {
        return $this->hasMany(Eclink::class, ['idEvent' => 'id']);
    }

    public function getComment()
    {
        return $this->hasMany(Comment::class, ['id' => 'idComment'])->with('author')->via('eclink');
    }

    public function getSubscription()
    {
        return $this->hasMany(Subscription::class, ['idEvent' => 'id']);
    }

    public function getSubscriptions()
    {
        return $this->hasMany(Profile::class, ['id' => 'idUser'])->via('subscription');
    }

    public function getCreator()
    {
        return $this->hasOne(Profile::class, ['id' => 'creatorId']);
    }

    public function getBook()
    {
        return $this->hasOne(Book::class, ['id' => 'bookId']);
    }

    public function getEvent($id)
    {
        return $this->findOne($id);
    }

    public function getEvents()
    {
        return $this->find()->orderBy('id')->all();
    }

    public function beforeSave($insert)
    {
        $this->creatorId  = Yii::$app->user->getId();
        $this->createDate = new Expression('now()');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
