<?php

namespace app\models\book;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Expression;

/**
 * This is the model class for table "{{%book}}".
 *
 * @property integer $id
 * @property string  $name
 * @property string  $description
 * @property string  $coverImage
 * @property integer $publish
 * @property integer $creatorId
 * @property string  $createDate
 */
class Book extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%book}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [
                [
                    'publish',
                    'creatorId',
                ],
                'integer',
            ],
            [
                ['createDate'],
                'safe',
            ],
            [
                [
                    'name',
                    'description',
                    'coverImage',
                ],
                'string',
                'max' => 255,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'          => 'ID',
            'name'        => 'Name',
            'description' => 'Description',
            'coverImage'  => 'Cover Image',
            'publish'     => 'Publish',
            'creatorId'   => 'Creator ID',
            'createDate'  => 'Create Date',
        ];
    }

    public function getBalink()
    {
        return $this->hasMany(Balink::class, ['idBook' => 'id']);
    }

    public function getBglink()
    {
        return $this->hasMany(Bglink::class, ['idBook' => 'id']);
    }

    public function getAuthor()
    {
        return $this->hasMany(Author::class, ['id' => 'idAuthor'])->via('balink');
    }

    public function getGenre()
    {
        return $this->hasMany(Genre::class, ['id' => 'idGenre'])->via('bglink');
    }

    public function beforeSave($insert)
    {
        $this->creatorId = Yii::$app->user->getId();
        $this->createDate = new Expression('now()');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
